cargo-features = ["edition2021"]

[package]
name = "echo"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
borsh = "0.9"
solana-program = "=1.9.1"
thiserror = "1.0.30"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
